# Generated by Django 3.1.7 on 2021-06-16 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='description',
            new_name='abilities',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='age',
            new_name='number',
        ),
    ]
